### ISSUE TITLE
Multiple languages support 

### ISSUE THREAD

**Issue by NeroBlackstone** [JuliaBooks/Books.jl#317]
Feature request

**Comment by rikhuijzer** [comment]
This was fixed in https://github.com/JuliaBooks/Books.jl/issues/60. At https://huijzer.xyz/Books.jl/other-notes you can see that the docs point now to https://juliadatascience.io/ for an example of a multilingual book.

Basically, what we do is we develop both books as stand-alone books and place one book at, for example, the main site and the other one at a prefix like `pt` (for Portugese). Then we publish both outputs to the same website. [Here](https://github.com/JuliaDataScience/JuliaDataScience-PT/blob/main/config.toml#L40) is the Portugese version with the 
```toml
 online_url_prefix = "pt"
```
And the Chinese version is [here](https://github.com/JuliaCN/JuliaDataScience/blob/main/config.toml). This site pushes to `https://cn.julialang.org`.
